# Yazi file manager configuration
# Docs: https://yazi-rs.github.io/docs/configuration/yazi

[manager]
ratio = [1, 4, 3]          # parent:current:preview
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
max_width = 600
max_height = 900
cache_dir = ""

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
    { name = "*.md", run = "code" },
]
